/**
 * Nama         : Gregorius Valentine
 * Nim          : H1051201012
 * Prodi        : Rekayasa Sistem Komputer
 * MataKuliah   : Analisa Algoritma
 * Tema Project : Input Data Mahasiswa
 */
package com.valentine.program;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Mahasiswa extends javax.swing.JFrame {
    
    private void kosongkan_form(){//FUNGSI UNTUK MENGOSONGKAN FORM   

        txtNIM.setEditable(true);
        txtNIM.setText(null);
        txtNAMA.setText(null);
        cbPRODI.setSelectedItem(this);
        txtALAMAT.setText(null);
        txtEMAIL.setText(null);
    }
    
    private void menampilkan_TabelMahasiswa(){
        
       //FUNGSI UNTUK MENAMPILKAN TABEL
       DefaultTableModel table=  new DefaultTableModel();
       table.addColumn("No.");
       table.addColumn("NIM");
       table.addColumn("Nama Mahasiswa");
       table.addColumn("Prodi");
       table.addColumn("Alamat");
       table.addColumn("Email");
       
       try
       {    
            int no = 1;
            //QUERY UNTUK MENAMPILKAN ISI TABLE DI DATABASE
            String QuerySql = "Select * FROM mahasiswa";
            //KONEKSI KE DATABASE
            java.sql.Connection conn = (com.mysql.jdbc.Connection)Config.configDB();
            //PEMBUATAN PERNYATAAN KONEKSI
            java.sql.Statement stm = conn.createStatement();
            //FUNGSI UNTUK MENGEKSEKUSI PERNYATAAN QuerySql KE DATABASE 
            java.sql.ResultSet rs = stm.executeQuery(QuerySql);
            
            //MENAMPILKAN ISI DATABASE KE TABEL MAHASISWA DENGAN MENGGUNAKAN ARRAY SESUAI DENGAN INDEX DI DATABASE DAN FORMAT TABLE MAHASISWA 
            while(rs.next())
            {
            table.addRow(new Object[]{no++,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
            }
            Tabel.setModel(table);
        }
        catch (SQLException e)
        {
            System.out.println("Error....! " + e.getMessage());
        }
    }

    /**
     * Creates new form Mahasiswa
     */
    
    public Mahasiswa() {
        
        initComponents();
        menampilkan_TabelMahasiswa();
        Mahasiswa.setDefaultLookAndFeelDecorated(rootPaneCheckingEnabled);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Judul = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jPanel_Properti = new javax.swing.JPanel();
        txtNAMA = new javax.swing.JTextField();
        txtNIM = new javax.swing.JTextField();
        txtALAMAT = new javax.swing.JTextField();
        txtEMAIL = new javax.swing.JTextField();
        cbPRODI = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        tbKELUAR = new javax.swing.JButton();
        tbSIMPAN = new javax.swing.JButton();
        tbEDIT = new javax.swing.JButton();
        tbCLEAR = new javax.swing.JButton();
        tbHAPUS = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Data Mahasiswa");
        setPreferredSize(new java.awt.Dimension(811, 490));
        setResizable(false);
        setSize(new java.awt.Dimension(811, 490));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Judul.setBackground(new java.awt.Color(51, 255, 0));
        jPanel_Judul.setForeground(new java.awt.Color(240, 240, 240));

        judul.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("DATA MAHASISWA");
        judul.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        judul.setFocusable(false);
        judul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel_JudulLayout = new javax.swing.GroupLayout(jPanel_Judul);
        jPanel_Judul.setLayout(jPanel_JudulLayout);
        jPanel_JudulLayout.setHorizontalGroup(
            jPanel_JudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        jPanel_JudulLayout.setVerticalGroup(
            jPanel_JudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel_Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 490, 40));

        jPanel_Properti.setBackground(new java.awt.Color(51, 255, 0));
        jPanel_Properti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel_Properti.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNAMA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNAMA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtNAMA.setVerifyInputWhenFocusTarget(false);
        jPanel_Properti.add(txtNAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 250, 30));

        txtNIM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNIM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtNIM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNIM.setVerifyInputWhenFocusTarget(false);
        txtNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIMActionPerformed(evt);
            }
        });
        jPanel_Properti.add(txtNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 250, 30));

        txtALAMAT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtALAMAT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtALAMAT.setVerifyInputWhenFocusTarget(false);
        jPanel_Properti.add(txtALAMAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 250, 30));

        txtEMAIL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEMAIL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtEMAIL.setVerifyInputWhenFocusTarget(false);
        jPanel_Properti.add(txtEMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 250, 30));

        cbPRODI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbPRODI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REKAYASA SISTEM KOMPUTER", "TEKNIK SIPIL", "BIOLOGI", "KIMIA", "MATEMATIKA", "ILMU KELAUTAN", "FISIKA", "" }));
        cbPRODI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cbPRODI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPRODIActionPerformed(evt);
            }
        });
        jPanel_Properti.add(cbPRODI, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 250, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("NAMA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel_Properti.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 66, 27));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("NIM");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel_Properti.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 66, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PRODI");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel_Properti.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 66, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("EMAIL");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel_Properti.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 66, 27));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ALAMAT");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel_Properti.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 66, 30));

        getContentPane().add(jPanel_Properti, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 360, 260));

        jPanel2.setBackground(new java.awt.Color(51, 255, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nim", "Nama", "Prodi", "Alamat", "Email"
            }
        ));
        Tabel.setPreferredSize(new java.awt.Dimension(272, 372));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 240));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 400, 260));

        jPanel3.setBackground(new java.awt.Color(51, 255, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbKELUAR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbKELUAR.setText("KELUAR");
        tbKELUAR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tbKELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKELUARActionPerformed(evt);
            }
        });
        jPanel3.add(tbKELUAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 130, 40));

        tbSIMPAN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbSIMPAN.setText("SIMPAN");
        tbSIMPAN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tbSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSIMPANActionPerformed(evt);
            }
        });
        jPanel3.add(tbSIMPAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 40));

        tbEDIT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbEDIT.setText("EDIT");
        tbEDIT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tbEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEDITActionPerformed(evt);
            }
        });
        jPanel3.add(tbEDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, 40));

        tbCLEAR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbCLEAR.setText("CLEAR");
        tbCLEAR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tbCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCLEARActionPerformed(evt);
            }
        });
        jPanel3.add(tbCLEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 130, 40));

        tbHAPUS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbHAPUS.setText("HAPUS DATA");
        tbHAPUS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tbHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHAPUSActionPerformed(evt);
            }
        });
        jPanel3.add(tbHAPUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 130, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 770, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/valentine/program/Latar.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbKELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKELUARActionPerformed
       
        //MENUTUP RUNNING YANG DILAKUKAN
           System.exit(0); 
        
    }//GEN-LAST:event_tbKELUARActionPerformed

    private void tbSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSIMPANActionPerformed

        //FUNGSI KETIKA TEXT FIELD KOSONG MAKA AKAN MEMUNCULKAN PEMBERITAHUAN
        if(txtNIM.getText().equals("")||txtNAMA.getText().equals("")||txtALAMAT.getText().equals("")||txtEMAIL.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Data Di Text Field Kosong, Silahkan Input Data Pada Text Field Terlebih Dahulu...!", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            try
            {
                String QuerySql = "INSERT INTO mahasiswa VALUES ('"+txtNIM.getText()+"','"+txtNAMA.getText()+"','"+cbPRODI.getSelectedItem()+"','"+txtALAMAT.getText()+"','"+txtEMAIL.getText()+"')";
                //KONEKSI KE DATABASE
                java.sql.Connection conn = (Connection)Config.configDB();
                //FUNGSI prepareStatement UNTUK SEBUAH PERNYATAAN QuerySql KE DATABASE
                java.sql.PreparedStatement pstm = conn.prepareStatement(QuerySql);
                //FUNGSI UNTUK MENGEKSEKUSI PERNYATAAN QuerySql KE DATABASE
                pstm.execute(); 
                JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil..", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                menampilkan_TabelMahasiswa();
                kosongkan_form();
            }
            catch(HeadlessException | SQLException e)
            {
                //PESAN ERROR JIKA PENGUJIAN TIDAK SESUAI
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_tbSIMPANActionPerformed

    private void tbEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEDITActionPerformed

        //FUNGSI KETIKA TEXT FIELD KOSONG MAKA AKAN MEMUNCULKAN PEMBERITAHUAN
        if(txtNIM.getText().equals("")||txtNAMA.getText().equals("")||txtALAMAT.getText().equals("")||txtEMAIL.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong, Untuk Edit Silahkan Klik Data Pada Tabel Terlebih Dahulu...!", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            try
            {
                //KONEKSI KE DATABASE
                java.sql.Connection conn = (Connection)Config.configDB();
                //QUERY SQL
                String QuerySql = "UPDATE mahasiswa SET nim='"+txtNIM.getText()+"',nama='"+txtNAMA.getText()+"',prodi='"+cbPRODI.getSelectedItem()+"',alamat='"+txtALAMAT.getText()+"',email='"+txtEMAIL.getText()+"' WHERE nim= '"+txtNIM.getText()+"'";
                //FUNGSI prepareStatement UNTUK SEBUAH PERNYATAAN QuerySql KE DATABASE
                java.sql.PreparedStatement pstm = conn.prepareStatement(QuerySql);
                //FUNGSI EXECUTE UNTUK MENGEKSEKUSI PERNYATAAN QuerySql KE DATABASE
                pstm.execute(); 
                JOptionPane.showMessageDialog(null, "Proses Edit Data Berhasil...!", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                menampilkan_TabelMahasiswa();
                kosongkan_form();
            }
            catch(HeadlessException | SQLException e)
            {
                //PESAN ERROR JIKA PENGUJIAN TIDAK SESUAI
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_tbEDITActionPerformed

    private void tbCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCLEARActionPerformed

        try
        {
            kosongkan_form();//MEMBERSIHKAN AREA TEXT FIELD
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tbCLEARActionPerformed

    private void tbHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHAPUSActionPerformed

        //FUNGSI KETIKA TEXT FIELD KOSONG MAKA AKAN MEMUNCULKAN PEMBERITAHUAN
        if(txtNIM.getText().equals("")||txtNAMA.getText().equals("")||txtALAMAT.getText().equals("")||txtEMAIL.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Data Di Tidak Boleh Kosong, Untuk Hapus Data Silahkan Klik Data Pada Tabel Terlebih Dahulu...!", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            try
            {
                //KONEKSI KE DATABASE
                java.sql.Connection conn = (Connection)Config.configDB();
                //QUERY SQL
                String QuerySql = "DELETE FROM mahasiswa WHERE nim='"+txtNIM.getText()+"'";
                //FUNGSI prepareStatement UNTUK SEBUAH PERNYATAAN QuerySql KE DATABASE
                java.sql.PreparedStatement pstm = conn.prepareStatement(QuerySql);
                //FUNGSI EXECUTE UNTUK MENGEKSEKUSI PERNYATAAN QuerySql KE DATABASE
                pstm.execute(); 
                JOptionPane.showMessageDialog(null, "Proses Hapus Data Berhasil..", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                menampilkan_TabelMahasiswa();
                kosongkan_form();
            }
            catch(HeadlessException | SQLException e)
            {
                //PESAN ERROR JIKA PENGUJIAN TIDAK SESUAI
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_tbHAPUSActionPerformed

    private void cbPRODIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPRODIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPRODIActionPerformed

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:

        int baris = Tabel.rowAtPoint(evt.getPoint());
        String nim = Tabel.getValueAt(baris, 1).toString();
        txtNIM.setText(nim);

        String nama = Tabel.getValueAt(baris, 2).toString();
        txtNAMA.setText(nama);

        String prodi = Tabel.getValueAt(baris, 3).toString();
        cbPRODI.setSelectedItem(prodi);

        String alamat = Tabel.getValueAt(baris, 4).toString();
        txtALAMAT.setText(alamat);

        String email = Tabel.getValueAt(baris, 5).toString();
        txtEMAIL.setText(email);

    }//GEN-LAST:event_TabelMouseClicked

    private void txtNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> cbPRODI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Judul;
    private javax.swing.JPanel jPanel_Properti;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JButton tbCLEAR;
    private javax.swing.JButton tbEDIT;
    private javax.swing.JButton tbHAPUS;
    private javax.swing.JButton tbKELUAR;
    private javax.swing.JButton tbSIMPAN;
    private javax.swing.JTextField txtALAMAT;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtNAMA;
    private javax.swing.JTextField txtNIM;
    // End of variables declaration//GEN-END:variables
}
